# Generated by Django 4.1.1 on 2022-12-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_chat_date_created_alter_message_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
