# Generated by Django 4.1.4 on 2022-12-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_chat_date_created_alter_message_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
