# Generated by Django 4.1.4 on 2022-12-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_activity_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='for_mood',
        ),
    ]
